# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of the integers from 10 to 50

In [2]:
array= np.arange(10,51)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


##find the memory size of any array

In [3]:
array.size

41

#### Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
array = np.arange(0,9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [5]:
array = np.identity(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Now do the following

Create list from 20 to 40

#### Get the mean of all the values in mat

In [6]:
l=np.arange(20,41)
print(l)
print(l.mean())

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
30.0


#### Get the median of all the columns in mat

In [8]:
print(np.median(l))

30.0


# Great Job!