<a href="https://colab.research.google.com/github/salmakhale/ML-Data-Analysis/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np


In [ ]:
a=np.array([[1,4,7],[2,5,8],[3,6,9]])
print(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
from numpy import random
rows=1
coulms=5
x=np.random.rand(rows,coulms)
print(x)

[[0.46976251 0.2215198  0.69999525 0.8089438  0.56718283]]


In [ ]:
original=([10,20,30])
After=([40,50,60,70,80,90])
np.append(original,After)


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7,8,9],[11,12,13]])
print(arr)
for x in np.nditer(arr):
  print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]
1
2
3
4
5
6
7
8
9
11
12
13


In [ ]:
arr1 = np.arange(6)
arr2 = arr1.reshape(2, 3)
print(arr1)
print(arr2)
for index, value in np.ndenumerate(arr2):
    print(f'Value: {value}, Position: {index}')



[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
Value: 0, Position: (0, 0)
Value: 1, Position: (0, 1)
Value: 2, Position: (0, 2)
Value: 3, Position: (1, 0)
Value: 4, Position: (1, 1)
Value: 5, Position: (1, 2)
